version: "3"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - "./backend:/app"
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"
      - "node_modules:/app/node_modules"
volumes:
  node_modules:
