name: CD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target: ["frontend", "backend"]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.target}}
          target: Dev
          cache-from: type=registry,ref=ghcr.io/${{ github.actor }}/quickroic/${{ matrix.target }}:latest
          cache-to: type=inline 
          push: true
          tags: ghcr.io/${{ github.actor }}/quickroic/${{ matrix.target }}:latest
  frontend:
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: pulling image
        run: docker pull ghcr.io/${{ github.actor }}/quickroic/frontend:latest
      - name: build react app
        run: mkdir $PWD/build && docker run ghcr.io/${{ github.actor }}/quickroic/frontend:latest -v $PWD/build:/app/build bash  -c "REACT_APP_GRAPHQL_ENDPOINT=${{secrets.REACT_APP_GRAPHQL_ENDPOINT }} yarn build" 
      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build