name: CI

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'main'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target: ["frontend", "backend"]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.target}}
          target: Dev
          cache-from: type=registry,ref=ghcr.io/${{ github.actor }}/quickroic/${{ matrix.target }}:ci
          cache-to: type=inline 
          push: true
          tags: ghcr.io/${{ github.actor }}/quickroic/${{ matrix.target }}:ci
  python:
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: pulling image
        run: docker pull ghcr.io/${{ github.actor }}/quickroic/backend:ci
      - name: linting
        run: docker run ghcr.io/${{ github.actor }}/quickroic/backend:ci make lint
      - name: testing
        run: docker run ghcr.io/${{ github.actor }}/quickroic/backend:ci make test
  js:
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: pulling image
        run: docker pull ghcr.io/${{ github.actor }}/quickroic/frontend:ci
      - name: linting
        run: docker run ghcr.io/${{ github.actor }}/quickroic/frontend:ci npx eslint src
      - name: testing
        run: docker run ghcr.io/${{ github.actor }}/quickroic/frontend:ci yarn test

