name: CI

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'master'
    
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: python lint
        run: docker-compose exec backend make lint
      - name: python test
        run: docker-compose exec backend make test
      - name: eslint
        run: docker-compose exec frontend npx eslint src
      - name: js test
        run: docker-compose exec frontend  yarn test
